version "4.11.0"

#include "zscript/belmondo/mathx/mathx.zs"
#include "zscript/belmondo/tob/util.zs"

#include "zscript/belmondo/tob/handler/game_info.zs"

#include "zscript/belmondo/tob/mixins/bullet_shooter.zs"
#include "zscript/belmondo/tob/mixins/amount_in_pickup_message.zs"
#include "zscript/belmondo/tob/mixins/flincher.zs"
#include "zscript/belmondo/tob/mixins/wolf3d_sized_actor.zs"
#include "zscript/belmondo/tob/mixins/weapons/grenade_thrower.zs"
#include "zscript/belmondo/tob/mixins/weapons/pill_taker.zs"
#include "zscript/belmondo/tob/mixins/weapons/kicker.zs"

#include "zscript/belmondo/tob/actor.zs"
#include "zscript/belmondo/tob/nazi_spawner.zs"
#include "zscript/belmondo/tob/particles.zs"
#include "zscript/belmondo/tob/bullet.zs"

#include "zscript/belmondo/tob/barrel.zs"

#include "zscript/belmondo/tob/inventory/ammo.zs"
#include "zscript/belmondo/tob/inventory/items.zs"
#include "zscript/belmondo/tob/inventory/keys.zs"
#include "zscript/belmondo/tob/inventory/powerups.zs"

#include "zscript/belmondo/tob/weapons/weapon.zs"
#include "zscript/belmondo/tob/weapons/reloading_weapon.zs"
#include "zscript/belmondo/tob/weapons/knife.zs"
#include "zscript/belmondo/tob/weapons/pistol.zs"
#include "zscript/belmondo/tob/weapons/dual_pistols.zs"
#include "zscript/belmondo/tob/weapons/machinegun.zs"
#include "zscript/belmondo/tob/weapons/rifle.zs"
#include "zscript/belmondo/tob/weapons/arifle.zs"
#include "zscript/belmondo/tob/weapons/chaingun.zs"
#include "zscript/belmondo/tob/weapons/bazooka.zs"
#include "zscript/belmondo/tob/weapons/flamethrower.zs"
#include "zscript/belmondo/tob/weapons/tesla.zs"
#include "zscript/belmondo/tob/weapons/portable_medkit.zs"

#include "zscript/belmondo/tob/projectiles.zs"
#include "zscript/belmondo/tob/grenade.zs"
#include "zscript/belmondo/tob/player.zs"

#include "zscript/belmondo/tob/inventory/component/bleedout.zs"
#include "zscript/belmondo/tob/inventory/component/flincher.zs"
#include "zscript/belmondo/tob/inventory/component/gusher.zs"

#include "zscript/belmondo/tob/monster/monster.zs"
#include "zscript/belmondo/tob/monster/nazi.zs"
#include "zscript/belmondo/tob/monster/boss.zs"
#include "zscript/belmondo/tob/monster/guard.zs"
#include "zscript/belmondo/tob/monster/dog.zs"
#include "zscript/belmondo/tob/monster/rifleman.zs"
#include "zscript/belmondo/tob/monster/officer.zs"
#include "zscript/belmondo/tob/monster/ssguard.zs"
#include "zscript/belmondo/tob/monster/mutant.zs"
#include "zscript/belmondo/tob/monster/skeleton.zs"
#include "zscript/belmondo/tob/monster/fire_skeleton.zs"
#include "zscript/belmondo/tob/monster/fake_hitler.zs"
#include "zscript/belmondo/tob/monster/grosse.zs"
#include "zscript/belmondo/tob/monster/olaric.zs"
#include "zscript/belmondo/tob/monster/super_soldier.zs"
#include "zscript/belmondo/tob/monster/harbinger.zs"

#include "zscript/belmondo/tob/post_processor.zs"
#include "zscript/belmondo/tob/menu.zs"
#include "zscript/belmondo/tob/hud.zs"
#include "zscript/belmondo/tob/intermission.zs"
#include "zscript/belmondo/tob/dont_change_music_marker.zs"

#include "zscript/belmondo/tob/handler/music_handler.zs"
#include "zscript/belmondo/tob/handler/player_death_handler.zs"
#include "zscript/belmondo/tob/handler/sod_handler.zs"
#include "zscript/belmondo/tob/handler/score_handler.zs"
#include "zscript/belmondo/tob/handler/toast_handler.zs"

#include "zscript/belmondo/tob/replacements/doom.zs"
#include "zscript/belmondo/tob/replacements/heretic.zs"
#include "zscript/belmondo/tob/replacements/wdcompat.zs"
